#pragma once

#include "VideoSource.hpp"

#include "../mobile/MobileStreamServer.hpp"

#include <cstddef>
#include <cstdint>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>


class VideoSourceManager
{
public:
    VideoSourceManager();

    ~VideoSourceManager();


    VideoSourceManager(
        const VideoSourceManager&
    ) = delete;


    VideoSourceManager& operator=(
        const VideoSourceManager&
    ) = delete;


    /*
     * =========================================================
     * SOURCE CREATION
     * =========================================================
     */

    std::string addLocalVideo(
        const std::string& filePath,
        const std::string& displayName
    );


    std::string addCamera(
        int cameraIndex,
        const std::string& displayName
    );


    std::string addRTSPStream(
        const std::string& url,
        const std::string& displayName
    );


    std::string addMobileStream(
        const std::string& displayName
    );


    /*
     * =========================================================
     * MOBILE STREAM
     * =========================================================
     */

    std::string getMobileStreamUrl(
        const std::string& sourceId
    ) const;


    bool isMobileStreamServerRunning()
        const noexcept;


    /*
     * =========================================================
     * MOBILE NETWORK TELEMETRY
     * =========================================================
     *
     * Returns the real network measurements generated by
     * MobileStreamServer.
     *
     * These measurements are available only for
     * VideoSourceType::MobileStream.
     */

    MobileNetworkStats getMobileNetworkStats(
        const std::string& sourceId
    ) const noexcept;


    /*
     * =========================================================
     * SOURCE LIFECYCLE
     * =========================================================
     */

    bool startSource(
        const std::string& sourceId
    );


    bool replayLocalVideo(
        const std::string& sourceId
    );


    void stopSource(
        const std::string& sourceId
    ) noexcept;


    void stopAll() noexcept;


    /*
     * =========================================================
     * FRAME ACCESS
     * =========================================================
     */

    bool tryGetFrame(
        const std::string& sourceId,
        Frame& frame
    );


    /*
     * =========================================================
     * SOURCE INFORMATION
     * =========================================================
     */

    const VideoSourceInfo* getSourceInfo(
        const std::string& sourceId
    ) const noexcept;


    VideoSourceState getSourceState(
        const std::string& sourceId
    ) const noexcept;


    /*
     * =========================================================
     * SOURCE MANAGEMENT
     * =========================================================
     */

    bool removeSource(
        const std::string& sourceId
    ) noexcept;


    std::size_t sourceCount()
        const noexcept;


    std::vector<std::string>
    sourceIds() const;


private:

    /*
     * =========================================================
     * SOURCE ID GENERATION
     * =========================================================
     */

    std::string generateSourceId();


private:

    /*
     * =========================================================
     * SOURCE STORAGE
     * =========================================================
     */

    mutable std::mutex m_mutex;


    std::unordered_map<
        std::string,
        std::unique_ptr<VideoSource>
    > m_sources;


    /*
     * =========================================================
     * MOBILE SERVER
     * =========================================================
     */

    std::unique_ptr<MobileStreamServer>
        m_mobileStreamServer;


    /*
     * =========================================================
     * SOURCE NUMBER
     * =========================================================
     */

    std::uint64_t m_nextSourceNumber = 1;
};